/* Word bank for Evie's typing game.
   Plain global array — loaded with <script src>, no fetch, no JSON.
   Keep words 3-6 letters, simple and picture-able. */

var WORDS = [
  { word: "cat",   emoji: "🐱" },
  { word: "dog",   emoji: "🐶" },
  { word: "sun",   emoji: "☀️" },
  { word: "fish",  emoji: "🐟" },
  { word: "ball",  emoji: "⚽" },
  { word: "star",  emoji: "⭐" },
  { word: "bus",   emoji: "🚌" },
  { word: "cow",   emoji: "🐮" },
  { word: "pig",   emoji: "🐷" },
  { word: "bee",   emoji: "🐝" },
  { word: "hat",   emoji: "🎩" },
  { word: "cup",   emoji: "🍵" },
  { word: "egg",   emoji: "🥚" },
  { word: "bed",   emoji: "🛏️" },
  { word: "car",   emoji: "🚗" },
  { word: "duck",  emoji: "🦆" },
  { word: "frog",  emoji: "🐸" },
  { word: "bear",  emoji: "🐻" },
  { word: "cake",  emoji: "🎂" },
  { word: "moon",  emoji: "🌙" },
  { word: "tree",  emoji: "🌳" },
  { word: "leaf",  emoji: "🍁" },
  { word: "milk",  emoji: "🥛" },
  { word: "boat",  emoji: "⛵" },
  { word: "bird",  emoji: "🐦" },
  { word: "apple", emoji: "🍎" },
  { word: "train", emoji: "🚂" },
  { word: "sheep", emoji: "🐑" },
  { word: "horse", emoji: "🐎" },
  { word: "mouse", emoji: "🐭" },
  { word: "heart", emoji: "❤️" },
  { word: "cloud", emoji: "☁️" },
  { word: "socks", emoji: "🧦" },
  { word: "banana", emoji: "🍌" },
  { word: "flower", emoji: "🌻" },
  { word: "rabbit", emoji: "🐰" },
  { word: "turtle", emoji: "🐢" },
  { word: "rocket", emoji: "🚀" },
  { word: "cheese", emoji: "🧀" },
  { word: "monkey", emoji: "🐵" }
];
